CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,15 +67,15 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v2
         with:
+          # required to check for changes
+          depth: 2
           submodules: false
-          # required to push changes
-          persist-credentials: true
-          # required to identify changed files
-          fetch-depth: 2
+          persist-credentials: false
 
       - name: Check for changes to hash/_wasm/
         id: source
         run: |-
+          set -o errexit
           shopt -s inherit_errexit
           declare modifications="$(git diff --name-only HEAD~ -- ./hash/_wasm/)"
           declare modified="$([[ "$modifications" ]] && echo true || echo false)"
@@ -101,12 +101,13 @@ jobs:
           cargo install -f wasm-bindgen-cli --version 0.2.74
         if: success() && steps.source.outputs.modified == 'true'
 
-      - name: Rebuild WASM
+      - name: Rebuild WASM and verify it's unchanged
         id: build
         if: success() && steps.source.outputs.modified == 'true'
         run: |-
           ./hash/_wasm/build.ts
 
+          set -o errexit
           shopt -s inherit_errexit
           declare modifications="$(git status --porcelain)"
           declare modified="$([[ "$(git status --porcelain)" ]] && echo true || echo false)"
@@ -114,33 +115,7 @@ jobs:
           echo "Generated code modified? $modified"
           echo "$modifications"
 
-      - name: Re-test hash/
-        run: deno test --unstable --allow-all ./hash
-        if: success() && steps.build.outputs.modified == 'true'
-
-      - name: Push changes
-        if: success() && steps.build.outputs.modified == 'true'
-        run: |
-          declare br="
-          "
-          shopt -s inherit_errexit
-          declare branch="$(echo ${GITHUB_HEAD_REF#refs/heads/})"
-          declare date="$(git log -1 --pretty=format:'%ad')"
-          declare author_name="$(git log -1 --pretty=format:'%an')"
-          declare author_email="$(git log -1 --pretty=format:'%ae')"
-          declare current_action_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}"
-
-          export GIT_AUTHOR_DATE="${date}"
-          export GIT_AUTHOR_NAME="${author_name}"
-          export GIT_AUTHOR_EMAIL="${author_email}"
-
-          export GIT_COMMITTER_DATE="${date}"
-          export GIT_COMMITTER_NAME="github-actions"
-          export GIT_COMMITTER_EMAIL="41898282+github-actions[bot]@users.noreply.github.com"
-
-          git remote rm origin
-          git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
-
-          git add .
-          git commit -m "chore(hash): rebuild wasm${br}${br}${current_action_url}"
-          git push --set-upstream origin "HEAD:${branch}"
+          if [[ "$modified" = "true" ]]; then
+            echo "::error ::Rebuilt WASM doesn't match committed WASM. Please rebuild and commit."
+            exit 1
+          fi
